---

- hosts: all
  become: true
  tasks:

  - name: apt install apache2 and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: dnf install apache and php packages
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["RedHat", "CentOS"]
