---

- hosts: all
  become: true
  tasks:

# Debian and Ubuntu    

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: remove php support for apache2
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

# RHEL and CentOS

  - name: dnf remove httpd
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: remove firewall rule for httpd service
    ansible.posix.firewalld: 
      service: http
      zone: public
      permanent: yes
      state: disabled
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: reload firewalld
    systemd:
      name: firewalld
      state: reloaded
    when: ansible_distribution in ["RedHat", "CentOS"]
